title: Site

tabs:
  pages:
    label: Pages
    icon: 📄
    preview: sections
    wysiwyg: true
    sections:
      pages:
        type: pages
        preview: fields
        wysiwyg: true

  navbar:
    label: Navigation
    preview: sections
    wysiwyg: true
    icon: 🚀
    sections:
      navbar:
        preview: fields
        wysiwyg: true
        type: fields
        fields:
          navbar:
            type: structure
            extends: sections/navbar
            max: 1

  footer:
    label: Footer
    preview: sections
    wysiwyg: true
    icon: ⚓️
    sections:
      footer:
        preview: fields
        wysiwyg: true
        type: fields
        fields:
          footer:
            type: structure
            extends: sections/footer
            max: 1

  cookies:
    label: Cookies
    preview: sections
    wysiwyg: true
    icon: 🍪
    sections:
      cookies:
        preview: fields
        wysiwyg: true
        type: fields
        fields:
          cookies:
            type: structure
            extends: sections/cookies
            max: 1

  taxonomies:
    label: Use Cases Taxonomies
    preview: sections
    wysiwyg: true
    icon: 🏷️
    sections:
      products:
        type: fields
        label: Products
        fields:
          products:
            type: structure
            label: Products List
            columns:
              name:
                width: 1/2
              slug:
                width: 1/2
            fields:
              name:
                type: text
                label: Name
              slug:
                type: slug
                label: Slug
                from: name

      industries:
        type: fields
        label: Industries
        fields:
          industries:
            type: structure
            label: Industries List
            columns:
              name:
                width: 1/2
              slug:
                width: 1/2
            fields:
              name:
                type: text
                label: Name
              slug:
                type: slug
                label: Slug
                from: name

      partners:
        type: fields
        label: Partners
        fields:
          partners:
            type: structure
            label: Partners List
            columns:
              name:
                width: 1/2
              slug:
                width: 1/2
            fields:
              name:
                type: text
                label: Name
              slug:
                type: slug
                label: Slug
                from: name

  blogTaxonomies:
    label: Blog Taxonomies
    preview: sections
    wysiwyg: true
    icon: 📚
    sections:
      blogCategories:
        type: fields
        label: Categories
        fields:
          categories:
            type: structure
            label: Categories List
            columns:
              name:
                width: 1/2
              slug:
                width: 1/2
            fields:
              name:
                type: text
                label: Name
              slug:
                type: slug
                label: Slug
                from: name

      blogProducts:
        type: fields
        label: Products
        fields:
          blogProducts:
            type: structure
            label: Products List
            columns:
              name:
                width: 1/2
              slug:
                width: 1/2
            fields:
              name:
                type: text
                label: Name
              slug:
                type: slug
                label: Slug
                from: name

  events:
    label: Events
    icon: 📅
    sections:
      events:
        type: fields
        fields:
          events:
            type: structure
            label: Events List
            fields:
              date:
                type: date
                label: Event Date
              author:
                type: text
                label: Author Name
              title:
                type: text
                label: Event Title
              image:
                type: files
                label: Event Image
                max: 1
              link:
                type: structure
                label: Event Link
                max: 1
                fields:
                  url:
                    type: text
                    label: URL
                  target:
                    type: select
                    label: Open in
                    options:
                      _self: Same Window
                      _blank: New Window
